export const userConstants = {
  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  LOGOUT: 'USERS_LOGOUT',

  GETALL_REQUEST: 'USERS_GETALL_REQUEST',
  GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
  GETALL_FAILURE: 'USERS_GETALL_FAILURE',

  DELETE_REQUEST: 'USERS_DELETE_REQUEST',
  DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
  DELETE_FAILURE: 'USERS_DELETE_FAILURE',

  UPDATE_USER_STATE: 'UPDATE_USER_STATE'
}

export const alertConstants = {
  SUCCESS: 'ALERT_SUCCESS',
  ERROR: 'ALERT_ERROR',
  CLEAR: 'ALERT_CLEAR'
}

export const boardConstants = {

}

export const listConstants = {
  ADD_LIST: 'ADD_LIST',
  GETTING_LIST: 'GETTING_LIST'
}
// Messages
export const MESSAGE_FAILURE = 'MESSAGE_FAILURE'
export const MESSAGE_SUCCESS = 'MESSAGE_SUCCESS'
export const MESSAGE_CLEAR = 'MESSAGE_CLEAR'
// Boards
export const ADD_BOARD_REQUEST = 'ADD_BOARD_REQUEST'
export const ADD_BOARD_SUCCESS = 'ADD_BOARD_SUCCESS'
export const ADD_BOARD_FAILURE = 'ADD_BOARD_FAILURE'

export const GET_BOARD_REQUEST = 'GET_BOARD_REQUEST'
export const GET_BOARD_FAILURE = 'GET_BOARD_FAILURE'
export const GET_BOARD_SUCCESS = 'GET_BOARD_SUCCESS'

export const UPDATE_CURRENT_BOARD_ID = 'UPDATE_CURRENT_BOARD_ID'
export const CHANGE_BOARD_TITLE = 'CHANGE_BOARD_TITLE'

export const DELETE_BOARD_REQUEST = 'DELETE_BOARD_REQUEST'
export const DELETE_BOARD_SUCCESS = 'DELETE_BOARD_SUCCESS'
export const DELETE_BOARD_FAILURE = 'DELETE_BOARD_FAILURE'
// List
export const ADD_LIST_REQUEST = 'ADD_LIST_REQUEST'
export const ADD_LIST_SUCCESS = 'ADD_LIST_SUCCESS'
export const ADD_LIST_FAILURE = 'ADD_LIST_FAILURE'

export const GET_LIST_REQUEST = 'GET_LIST_REQUEST'
export const GET_LIST_FAILURE = 'GET_LIST_FAILURE'
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS'

export const DELETE_LIST_REQUEST = 'DELETE_LIST_REQUEST'
export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS'
export const DELETE_LIST_FAILURE = 'DELETE_LIST_FAILURE'

export const CHANGE_LIST_TITLE_REQUEST = 'CHANGE_LIST_TITLE_REQUEST';
export const CHANGE_LIST_TITLE_SUCCESS = 'CHANGE_LIST_TITLE_SUCCESS';

export const MOVE_LIST_REQUEST = 'MOVE_LIST_REQUEST';
export const MOVE_LIST_SUCCESS = 'MOVE_LIST_SUCCESS';
//Cards
export const GET_CARD_REQUEST = 'GET_CARD_REQUEST';
export const GET_CARD_SUCCESS = 'GET_CARD_SUCCESS';

export const ADD_CARD_REQUEST = 'ADD_CARD_REQUEST';
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS';

export const CHANGE_CARD_TITLE_REQUEST = 'CHANGE_CARD_TITLE_REQUEST';
export const CHANGE_CARD_TITLE_SUCCESS = 'CHANGE_CARD_TITLE_SUCCESS';

export const DELETE_CARD_REQUEST = 'DELETE_CARD_REQUEST';
export const DELETE_CARD_SUCCESS = 'DELETE_CARD_SUCCESS';

export const MOVE_CARD_REQUEST = 'MOVE_CARD_REQUEST';
export const MOVE_CARD_SUCCESS = 'MOVE_CARD_SUCCESS';

export const ADD_MEMBER_REQUEST = 'ADD_MEMBER_REQUEST';
export const REMOVE_MEMBER_REQUEST = 'REMOVE_MEMBER_REQUEST';
export const UPDATE_MEMBER_SUCCESS = 'UPDATE_MEMBER_SUCCESS';
